server:
  port: 8088

spring:
  application:
    name: WordGames
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

wordgames:
  cache-path: ${APP_CACHE_PATH:~/appdata/wordgames/cache}